name: CostcoScanner
options:
  bundleIdPrefix: com.costcoscanner
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
targets:
  CostcoScanner:
    type: application
    platform: iOS
    sources: [CostcoScanner]
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_FILE: CostcoScanner/Info.plist
        INFOPLIST_KEY_CFBundleDisplayName: "CostScanner"
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        DEVELOPMENT_TEAM: ""
        PRODUCT_BUNDLE_IDENTIFIER: com.costcoscanner.app
        SWIFT_VERSION: "5.9"
        TARGETED_DEVICE_FAMILY: "1,2"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
